version: '3'

services:
  machine-learning:
    container_name: machine-learning-service
    build:
      context: ./MACHINE-LEARNING-SERVICE
      dockerfile: machine-learning.Dockerfile
    restart: always
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      SERVER_URL: http://localhost:3000/api/v1
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-network

networks: 
  mongo-network:
    driver: bridge